// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Follower struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
}

type User struct {
	ID             uuid.UUID
	Name           string
	Username       string
	Email          string
	Password       string
	Bio            sql.NullString
	Profession     sql.NullString
	IsVerified     sql.NullBool
	IsActive       sql.NullBool
	ProfilePicture sql.NullString
	CoverPicture   sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}
