// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Bookmark struct {
	Username string
	PostID   uuid.UUID
}

type Comment struct {
	ID          uuid.UUID
	CommentText string
	Media       json.RawMessage
	Username    string
	PostID      uuid.UUID
	LikesCount  int32
	ReplyCount  int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type CommentLike struct {
	Username  string
	CommentID uuid.UUID
}

type CommentReply struct {
	ID         uuid.UUID
	ReplyText  string
	Media      json.RawMessage
	Username   string
	CommentID  uuid.UUID
	LikesCount int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Follower struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
}

type Like struct {
	PostID   uuid.UUID
	Username string
}

type Notification struct {
	ID                  uuid.UUID
	SenderUsername      string
	ReceiverUsername    string
	Content             string
	CreatedAt           time.Time
	IsViewed            bool
	NotificationsSource string
	Reference           string
}

type Post struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Content        string
	Media          json.RawMessage
	Username       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LikesCount     int32
	CommentCount   int32
	BookmarksCount int32
	ShareCount     int32
	IsSharedPost   bool
	SharedPostID   uuid.NullUUID
}

type User struct {
	ID             uuid.UUID
	Name           string
	Username       string
	Email          string
	Password       string
	Bio            sql.NullString
	Profession     sql.NullString
	IsVerified     sql.NullBool
	IsActive       sql.NullBool
	ProfilePicture sql.NullString
	CoverPicture   sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}
