// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: posts.sql

package database

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const newPost = `-- name: NewPost :one

INSERT INTO posts (
    id, user_id, username, content, media, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, content, media, username, created_at, updated_at
`

type NewPostParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Username  string
	Content   string
	Media     json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) NewPost(ctx context.Context, arg NewPostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, newPost,
		arg.ID,
		arg.UserID,
		arg.Username,
		arg.Content,
		arg.Media,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Media,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
